name: Build and Push Docker Image to Docker Hub

on:
  release:
    types: [published]

env:
  DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/walauncher

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract release version
        id: extract_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_REPO }}:${{ env.RELEASE_VERSION }} .
          docker tag ${{ env.DOCKER_REPO }}:${{ env.RELEASE_VERSION }} ${{ env.DOCKER_REPO }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ env.DOCKER_REPO }}:${{ env.RELEASE_VERSION }}
          docker push ${{ env.DOCKER_REPO }}:latest
